#
#	AUTHORED BY:  Elliott Hager
#


COMPILER = g++

FLAGS = --std=c++17

SOURCE = testHashmap.cpp

OUTPUT = hashMap



build:
	$(COMPILER) $(FLAGS) $(SOURCE) -o $(OUTPUT)




clean:
	rm -f $(OUTPUT)

